# Configuration for training the Hunyuan3D-Glasses model

# Data configuration
data:
  data_dir: "data"
  num_workers: 4
  img_size: 224
  num_points: 2048

# Model configuration
model:
  latent_dim: 512

# Training configuration
training:
  batch_size: 32
  learning_rate: 0.0001
  weight_decay: 0.0001
  num_epochs: 100
  fine_tune: false
  freeze_encoder: false
